package com.groupon.web.dao.model;

public enum NotificationType {
	TASK_CREATED_IN_FOLLOWED_COMMUNITY, //
	TASK_REPLY, //
	TASK_COMMENT, //
	TASK_DELETED, //
	COMMUNITY_DELETED, //
	TASK_UPVOTE, //
	TASK_DOWNVOTE, //
	TASK_REPLY_ACCEPTED, //
	TASK_REPLY_UPVOTE, //
	TASK_REPLY_DOWNVOTE;
}
